version: "3"

services:
  api:
    build: .
    restart: 'always'
    ports:
      - "8080:8080"
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    volumes: 
      - ./swagger.yaml:/swagger/swagger.yaml
    environment:
      SWAGGER_JSON: /swagger/swagger.yaml